### ISSUE TITLE
No such file or directory - drafter

### ISSUE THREAD

**Issue by walbertus** [funbox/tomograph#20]
When running script:
```
tomograph doc.apib doc.json
```

Produce error:
```
No such file or directory - drafter
```

**Comment by walbertus** [comment]
To solve this you need to install `drafter`.

**Comment by tuwilof** [comment]
Thanks for your feedback, we improved README
https://github.com/funbox/tomograph/commit/ec7baa7f5615cdfbb55d91bf1976f0831b40430a
