### ISSUE TITLE
support multi request for one resource path

### ISSUE THREAD

**Issue by kuznetsov-v-spb** [funbox/tomograph#27]
Привет.

Для одного из проектов в Funbox появилась необходимость для одного `resource path` указать несколько типов запросов. В данном случае запросы имеют разную структуру, а один из них содержит много параметров и несколько возможных вариантов, которые записываются через `One Of`.

Чтобы описать такие запросы есть 3 варианта:
1) Удобнее всего сделать 3 файла в с одинаковым `resource path` и описать эти типы запросов раздельно. В таком случае генерируемый HTML из APIB получается самый читабельный и удобный.
2) Чуть менее читабельный но приемлемый вариант это сделать 1 файл, в котором указать несколько блоков `Request`.
3) Сделать 1 файла, в котором описан 1 запрос где все варианты запросов указываются через `One Of`. В таком случае HTML из APIB получается не очень удобный, слишком много вариантов и очень мало комментарий влезает.

Все 3 варианта поддерживаются в APIB и генерация HTML также проходит успешно.

С 1 и 2 вариантом проблема в том, что при конвертации из `.apib` в `.json` несколько типов запросов для одного `resource path` не сохраняются в `json` схеме (json схема у нас используется в реализации для проверки соответствия API через plumbapius)

Конвертацию делаем в 2 этапа:
Этап 1: `npx @funbox/crafter "../doc.apib" > "doc.yml"`
На данном этапе для 1 варианта мы получим предупреждение `Warning at line 1 (see ...): The resource "/WEBHOOK_URL{?chatbot}" is already defined` но в "doc.yml" все запросы корректно добавляются + сами предупреждения будут также добавлены в конце файла. Для 2 варианта предупреждений нет и всё запросы добавляются в "doc.yml".

Этап 2: `tomograph -d crafter --exclude-description "doc.yml" "doc.json"`
После конвертации из "doc.yml" в "doc.json" для одного `resource path` остаётся только 1 запрос. При этом в списке ответов для 1 варианта добавляются ответы из всех 3 файлов и, например, в нашем случае в атрибуте `responses` указано 3 одинаковых ответа с кодом 200.

На сколько понял `tomograph` изначально считает, что одному `resource path` соответствует только 1 запрос.

Возможно ли как-то решить эту проблему при конвертации с помощью настроек `crafter` или `tomograph`? Если нет то наверное стоит добавить поддержку нескольких типов запросов для одного `resource path` в `tomograph`.

P.S.: Также наверное следует учесть, что чисто теоретически для одного resource path для разных типов запросов могут быть разные типы ответов. В таком случае нужно будет обязательно описывать разные файлы .apib с одним `resource path`и разными парами запросов и ответов, а при конвертации в .json соответствие пар запросов и ответов должно сохраняться.

**Comment by tuwilof** [comment]
Привет, да ранее похожие идеи обсуждались
Ну в целом концептуально, и сам API Blueprint ругается на несколько запросов в одном, такое как правило пораждает много багов при реализации бекенда, и мы стараемся разделять на несколько самостоятельных запросов, что упрощает поддержку и тестирование к тому же

Но если все же рассмотреть наличие нескольких запросов в одном, важное обратить внимание на content-type. Если они отличаются в рамках одного запроса, то можно на этом уровне сделать подмножество запросов.

Ну либо да, можно добавить возможность и свободу для анархии, делать множество запросов в одном. Мне конечно не нравится что в таком случае API скорее всего будет далеко от REST и практика показывает что чаще эта возможность будет приводить к плохим реализациям. Честно говоря думал в crafter запретили такое, а не только ограничились предупреждением как в drafter. В swagger/open API с этим совсем строго, даже подмножество ответов делать нельзя.
Ну если уж очень хочется, так как других путей нет, кроме как разделить запрос на три, можно поправить tomograph, но только если будет сообщение в консоли о предупреждении, что это не очень хорошо. Но это будет мажорный релиз, и надо немного поправить связанные библиотеки.

Но последний пункт PS, конечно, лишний раз показывает что если хочется разные запросы и ответы связать между собой, то надо делать отдельные запросы и ответы 😄 
Поэтому предлагаю все таки сначала подробнее обсудить, почему запрос нельзя поделить на несколько? Можем обсудить приватно в slack.

**Comment by tuwilof** [comment]
Касательно этого момента в проекте стараемся придерживаться следующих правил

> 6. Больше запросов -- богу запросов
> 
> 6.1. В любой непонятной ситуации добавляйте методы
> 
> Больше методов хороше, потому что через интерфейс становится все видно и прозрачно, используется главная особенно и достоинство REST.
> 
> 6.2. Если хочется if/else внутри обработки запроса, сделайте два запроса
> 
> Незачем скрывать из интерфейса логику, лучше сделай два метода. Тестировать отделу качеству будет проще, так как больше кейсов будет видно. Раньше можно будет обнаружить лишние кейсы, и мб окажется что какие то операции обрабатывать и не нужно вовсе.
> 
> 6.3. Не используйте oneOf в запросах
> 
> Да в этом случае в интерфейсе логика будет прозрачна, но зачем горадить огород, и перегружать одну точку интерфейса.
> Ответов это не касатеся, oneOf в ответах это нормальная практика.
>

**Comment by tuwilof** [comment]
Ок, в итоге выяснили что нужно описать предоставляемое API, которое имеют свою спецификацию, и для нее нужна валидация для https://github.com/funbox/plumbapius
Подготовил пыр, еще заодно нужно сделать задачку #29 и выкачу новую версию с поддержкой такого описания

```
# Microservice
## Recommendation [/recommendation]
### To viewing [GET]
+ Request (application/json)
    + Attributes
      + tv_series: Mr. Robot (string, required)

+ Request (application/json)
    + Attributes
      + cinema: The Nice Guys (string, required)

+ Response 200 (application/json)
```

Результат которых теперь будет такой
```
[
  {
    "path": "/recommendation",
    "method": "GET",
    "content-type": "application/json",
    "requests": [
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "properties": {
          "tv_series": {
            "type": "string"
          }
        },
        "required": [
          "tv_series"
        ]
      },
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "properties": {
          "cinema": {
            "type": "string"
          }
        },
        "required": [
          "cinema"
        ]
      }
    ],
    "responses": [
      {
        "status": "200",
        "body": {},
        "content-type": "application/json"
      }
    ],
    "resource": "/recommendation"
  }
]
```
